[package]
name = "anim2d"
version = "0.1.0"
authors = ["Cassie Wang <cassandra.wang@pomona.edu>"]
edition = "2018"

[dependencies]
pixels = "0.2.0"
winit = "0.22.0"
winit_input_helper = "0.6.0"
image = "0.23.12"